### ISSUE TITLE
mvn package build issue

### ISSUE THREAD

**Issue by spicysomtam** [ewolff/microservice-kafka#1]
I am getting this issue with the build:

```
2017-08-23 09:00:25.822 ERROR 11897 --- [           main] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='{  "id" : 1,  "customer" : {    "customerId" : 1,    "name" : "Wolff",    "firstname" : "Eberhard", ...' to topic order:

org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

I use Linux Mint (ubuntu based distro). Everything is pretty up to date. Maybe a port is in use, or I am missing something? Or is it the 'null' that is a problem?

I tried a fresh build with `mvn -X package` and redirected the output. Could not see anything obvious. Maybe you can try and rebuild it and see if anything has changed?

**Comment by ewolff** [comment]
I just did `git pull` and `mvn clean package` and it works. Try to look for something like `bootstrap.servers = [127.0.0.1:64695]` in the output. That is the port the embedded Kafka in the tests uses. Make sure that port is accessible and not used by another server. Hope this helps!

**Comment by spicysomtam** [comment]
I just upgrade mvn from 3.3.9 to 3.5, and apart from nice pretty colours, its the same issue. 

BTW what platform do you use for developing?

In the logging do you see this kafka version:

```
Kafka version : 0.10.1.1
```
Latest is 0.11.0.0

**Comment by spicysomtam** [comment]
Back from a standup. Still think its something to do with this:
```
2017-08-23 09:59:36.310 ERROR 17101 --- [           main] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='{  "id" : 1,  "customer" : {    "customerId" : 1,    "name" : "Wolff",    "firstname" : "Eberhard", ...' to topic order:
```
Maybe I can skip the tests?

**Comment by ewolff** [comment]
Of course you can skip the tests - the code should work. The Kafka
server in production is a different one i.e. not embedded.

**Comment by spicysomtam** [comment]
I am not a java developer for starters (linux sysadmin/devops). However I managed to skip the tests using this, and get the jars to build:

```
mvn package -DskipTests=true
```

Docker compose now comes up.

**Comment by ewolff** [comment]
I updated the documentation to include this hint. Thanks for pointing this out.
