### ISSUE TITLE
Question: use of `-XX:TieredStopAtLevel=1 -noverify`

### ISSUE THREAD

**Issue by simbo1905** [ewolff/microservice-kafka#12]
Hello. I see that the Docker starts things with jvm flags `-XX:TieredStopAtLevel=1 -noverify` I can see how that might help with startup time and possibly memory. Seems that folks might copy those settings and I am wondering if they are recommended for production or simply there for fast demos?

**Comment by ewolff** [comment]
This is a demo. Settings are not intended for production. This is in particular true for Kafka and Postgres. See https://github.com/dsyer/spring-boot-startup-bench for the optimization concerning startup time.

I'll close the issue, reopen if needed.
