### ISSUE TITLE
docker compose fails

### ISSUE THREAD

**Issue by DanStadlerNewRelic** [ewolff/microservice-kafka#14]
when trying out the docker compose section, I get this failure:

> Building order
> Step 1/4 : FROM openjdk:11.0.2-jre-slim
> 11.0.2-jre-slim: Pulling from library/openjdk
> 27833a3ba0a5: Pull complete
> 16d944e3d00d: Pull complete
> 6aaf465b8930: Pull complete
> 0684138f4cb6: Pull complete
> 67c4e741e688: Pull complete
> 783178df3a0c: Pull complete
> Digest: sha256:da5605d071e9e41803f8b45f41f8c24ad6c26056190a871c8d6471982407d05b
> Status: Downloaded newer image for openjdk:11.0.2-jre-slim
>  ---> b7a931ed7d37
> Step 2/4 : COPY target/microservice-kafka-order-0.0.1-SNAPSHOT.jar .
> ERROR: Service 'order' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder600758216/target/microservice-kafka-order-0.0.1-SNAPSHOT.jar: no such file or directory

**Comment by ewolff** [comment]
Please make sure the Maven build step works before building the Docker containers. The error is cause by the missions build artefacts of the Maven build, see #13 . Please reopen if this does not help.
