### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by marcbuchser** [ewolff/microservice-kafka#15]
After building with maven and the docker build -> docker compose up -d 

invoicing and shipping exit with code 1 and the call to localhost:8080 - clicking on order results in:
>>>>>>>
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: order

Apache/2.4.18 (Ubuntu) Server at localhost Port 80

**Comment by marcbuchser** [comment]
resolved. 
the init-user-db.sh was not executed properly....manually created them and then it worked - probably a windwos CR/LF issue.

**Comment by ewolff** [comment]
Thanks for reaching out and reporting the problem - glad it works!
