### ISSUE TITLE
I want to change db from postgresql to mysql.

### ISSUE THREAD

**Issue by isushilksharma** [ewolff/microservice-kafka#16]
Is there any way to change postgres db to mysql. I was trying to do so but it's not working, can you help me out for this.

**Comment by ewolff** [comment]
You will need to do the following:
- Add a MySQL Docker image to `docker-compose.yml`
- Replace the Postgres driver in the `pom.xml` files
- Replace the Postgres configuration with a MySQL configuration in the `application.properties`files
