### ISSUE TITLE
Request without post or get 

### ISSUE THREAD

**Issue by akondasif** [ewolff/microservice-kafka#18]
Hi @ewolff ,

We followed your recommendations from [this issue](https://github.com/ewolff/microservice/issues/28) and found a few instances of request method without get or post

Source: 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-shipping/src/main/java/com/ewolff/microservice/shipping/web/ShippingController.java#L28 

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-order/src/main/java/com/ewolff/microservice/order/logic/OrderController.java#L45

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-invoicing/src/main/java/com/ewolff/microservice/invoicing/web/InvoiceController.java#L28

**Comment by ewolff** [comment]
As mentioned https://github.com/ewolff/microservice/issues/28#issuecomment-654375293 I don't think this is a security problem. Please reopen if you have different information. Thanks.

**Comment by ewolff** [comment]
Actually you are right. Sorry.

**Comment by akondasif** [comment]
No need to apologize. Thanks for the feedback.
