### ISSUE TITLE
Passwords in `.properties` file 

### ISSUE THREAD

**Issue by akondasif** [ewolff/microservice-kafka#19]
Hi @ewolff , 

Our tool detected some instances of passwords in `.properties` file. Wanted to bring it to your attention: 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-invoicing/src/test/resources/application-test.properties#L4

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-invoicing/src/main/resources/application.properties#L13

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-order/src/test/resources/application-test.properties#L6

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-order/src/main/resources/application.properties#L11

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-shipping/src/test/resources/application-test.properties#L4

and 

https://github.com/ewolff/microservice-kafka/blob/918d5387daa7242f0b1a741c7d772142093a0ceb/microservice-kafka/microservice-kafka-shipping/src/main/resources/application.properties#L13

**Comment by ewolff** [comment]
Actually that is even the default password for the official Postgres Docker image that I am using. I do see the point but this demo is a demo - no production code.
