### ISSUE TITLE
 returned a non-zero code: 137

### ISSUE THREAD

**Issue by viprud** [ewolff/microservice-kafka#20]
I keep getting this error when trying to docker-compose build

Is there any issue with the file /apache/Dockerfile ?

ERROR: Service 'apache' failed to build: The command '/bin/sh -c apt-get install -y -qq apache2 &&     a2enmod proxy proxy_http proxy_ajp rewrite deflate headers proxy_connect proxy_html lbmethod_byrequests &&     mkdir /var/lock/apache2 && mkdir /var/run/apache2' returned a non-zero code: 137

Docker version 19.03.12, build 48a66213fe

**Comment by ewolff** [comment]
The CI build now works. It generates the Docker images from scratch, see https://github.com/ewolff/microservice-kafka/actions . So I don't think there is a problem with the code but rather with your machine. I will therefore close the issue. Feel free to reopen if you find any hints that this is in fact a problem with the code.
