### ISSUE TITLE
Starting mskafka_zookeeper_1 ... error  ERROR: for mskafka_zookeeper_1  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (de37724a560282572b4e7698cc26e584e0709fb4bb1401beef02cda986e894da): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error  ERROR: for zookeeper  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (de37724a560282572b4e7698cc26e584e0709fb4bb1401beef02cda986e894da): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by rajkumarkanjo** [ewolff/microservice-kafka#9]
D:\Raj_Codings\microservice-kafka-master\docker>**docker-compose up -d**
mskafka_postgres_1 is up-to-date
Starting mskafka_zookeeper_1 ... error

ERROR: for mskafka_zookeeper_1  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (de37724a560282572b4e7698cc26e584e0709fb4bb1401beef02cda986e894da): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error

ERROR: for zookeeper  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (de37724a560282572b4e7698cc26e584e0709fb4bb1401beef02cda986e894da): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error
ERROR: Encountered errors while bringing up the project.

D:\Raj_Codings\microservice-kafka-master\docker>docker-machine create --virtualbox-memory "4096" --driver virtualbox dev
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"

**Comment by ewolff** [comment]
For the first command: No proxy on port 2181 could be created. Make sure no process is running on that port. You could for example restart the machine. It could also be that you have already started the Docker containers and they still run in the background.

For the second command: If you want to create a VirtualBox VM, you need to install VirtualBox first. I am actually not sure why you are starting Docker Machine. The documentation does not say anything about Docker Machine.

I am afraid that I don't see how the project should be changed based on this issue. I will therefore close it. Feel free to reopen it or file other issues. Thanks!

**Comment by rajkumarkanjo** [comment]
D:\Raj_Codings\microservice-kafka-master\docker>docker-compose up -d
Starting mskafka_zookeeper_1 ...
Starting mskafka_zookeeper_1 ... error

ERROR: for mskafka_zookeeper_1  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (dff1be64031b3f3000ce7883c2175cd35750434a5be034ddcccd2a7bdd231648): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error

ERROR: for zookeeper  Cannot start service zookeeper: driver failed programming external connectivity on endpoint mskafka_zookeeper_1 (dff1be64031b3f3000ce7883c2175cd35750434a5be034ddcccd2a7bdd231648): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:2181:tcp:172.18.0.3:2181: input/output error
ERROR: Encountered errors while bringing up the project.

=================>>>
As you have said i have checked all the running port. No process in port 2181and Docker containers is closed. I have followed up your all the instruction line by line but i am stuck here. Please help me out i want to understand this project .

**Comment by rajkumarkanjo** [comment]
clarifiaction: To run this project do i need docker to be installed in my system..?

**Comment by ewolff** [comment]
Yes, you need Docker installed.

**Comment by ewolff** [comment]
Actually the port was not needed. I removed the port mapping so this problem should be fixed. See fac87ad69a61ce0999029e0a363ca181aa8b819d
